#
# Used to update the OS and to configure it to fit UNIX requirements
#
- name: Cluster Nodes Prerequisites
  hosts: all
  any_errors_fatal: yes
  gather_facts: no
  become: true
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
    no_proxy: "{{ no_proxy | default('') }}"
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
  roles:
    - nodes_preq


