#
#  Cluster nodes prerequisites
#
- import_playbook: nodes_preq.yml

#
#  Used to deploy RKE cluster
#
- import_playbook: rke.yml

#
#  Used to install rancher manager
#
- import_playbook: rnc_mgmt.yml
