---

- name: Update yum cache
  ansible.builtin.yum:
    update_cache: true

- name: Install keepalive
  ansible.builtin.package:
    name: keepalived

- name: Create directory for keepalived
  file:
    path: /etc/keepalived
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create Kubernetes API health check script
  template:
    src: templates/check_apiserver.sh.j2
    dest: /etc/keepalived/check_apiserver.sh
    owner: root
    group: root
    mode: 0755

- name: restart keepalived
  service:
    name: keepalived
    state: restarted

- name: Create keepalived config file
  template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644

- name: Enable keepalived and make sure it is not masked
  systemd:
    name: keepalived
    enabled: yes
    masked: no

- name: restart keepalived
  service:
    name: keepalived
    state: restarted


- name: Flush handlers
  meta: flush_handlers
