---
- name: Download kubectl
  get_url:
    url: https://dl.k8s.io/release/v1.23.2/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
  register: result
  until: result.failed != true
  retries: 10
  delay: 1

- name: Add Kubectl alias
  lineinfile:
    path: /root/.bashrc
    line: "alias k='kubectl'"
    owner: root
    state: present
    insertafter: EOF
    create: True
