---
- include_tasks: chrony.yml

- include_tasks: network_manager.yml

- include_tasks: sysctl.yml

## not necessary
#- include_tasks: docker.yml

- include_tasks: yum_packages.yml

- import_tasks: helm.yml
  tags: helm

- import_tasks: kubectl.yml

- include_tasks: disable_firewall.yml

- include_tasks: disable_selinux.yml