---
- import_tasks: chrony.yml

- import_tasks: network_manager.yml

- import_tasks: sysctl.yml

## not necessary
#- import_tasks: docker.yml

- import_tasks: yum_packages.yml

- import_tasks: helm.yml
  tags: helm

- import_tasks: kubectl.yml

- import_tasks: disable_firewall.yml

- import_tasks: disable_selinux.yml