---

- name: Download and install RKE2
  import_tasks: rke2.yml

#- name: 'Stop execution'
#  fail: msg="Desired stop"

- name: Find Active Server
  import_tasks: find_active_server.yml

- name: Prepare very first server node in the cluster
  import_tasks: first_server.yml
  when:
    - inventory_hostname == groups[rke_servers_group_name].0
    - active_server is not defined

- name: Prepare and join remaining nodes of the cluster
  import_tasks: remaining_nodes.yml
  when:
    - active_server is defined
    - groups[rke2_cluster_group_name] | length | int >= 2

- name: Final steps
  import_tasks: summary.yml
