---
- name: Download RKE2 installation script
  ansible.builtin.get_url:
    url: "{{ rke2_install_bash_url }}"
    dest: /tmp/rke2.sh
  register: result
  until: result.failed != true
  retries: 10
  delay: 1
#  ignore_errors: yes

#- name: Print service facts
#  ansible.builtin.debug:
#    var: result.failed
#- meta: end_play

- name: Set the permissions for the file
  file:
    dest: /tmp/rke2.sh
    mode: 0700

- name: Populate service facts
  service_facts:

- name: Check RKE2 version
  shell: |
    set -o pipefail
    /usr/local/bin/rke2 --version | grep -E "rke2 version" | awk '{print $3}'
  args:
    executable: /bin/bash
  changed_when: false
  register: installed_rke2_version
  when: '"rke2-server.service" in ansible_facts.services'

- name: Run RKE2 script
  command:
    cmd: /tmp/rke2.sh
  environment:
    INSTALL_RKE2_VERSION: "{{ rke2_version }}"
    INSTALL_RKE2_CHANNEL_URL: "{{ rke2_channel_url }}"
    INSTALL_RKE2_CHANNEL: "{{ rke2_channel }}"
    INSTALL_RKE2_METHOD: "{{ rke2_method }}"
  when: (rke2_version != ( installed_rke2_version.stdout | default({})))
        or installed_rke2_version is not defined

- name: Creates directory rke2/server/manifests
  file:
    path: /var/lib/rancher/rke2/server/manifests/
    state: directory
    owner: root
    group: root
    mode: 0644
    recurse: yes

- name: Copy Custom Manifests
  copy:
    src: "{{ item }}"
    dest: /var/lib/rancher/rke2/server/manifests/
    owner: root
    group: root
    mode: 0644
  with_items: "{{ rke2_custom_manifests }}"
  when: rke2_custom_manifests

#- name: Copy nginx Manifests
#  copy:
#    src: nginx.yml
#    dest: /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml
#    owner: root
#    group: root
#    mode: 0644
