---
kubernetes_version: "v1.21.9-rancher1-1"
cluster_name: rnc_lab_mgmt

# Network configuration
# Pod networks
kube_cni_pod: "10.171.0.0/16"

# Services network
kube_cni_services: "10.172.0.0/16"

# DNS Service
cluster_dns_server: "10.172.0.10"

rke_config_dir: "/root/rke"
rke_release: v1.3.7
rke_binary_url: "https://github.com/rancher/rke/releases/download/{{ rke_release }}/rke_linux-amd64"
rke_binary_checksum: sha256:07a7162d654c84235e06a132caff465f17c206654e7bdf10821912d1c068e7cf
rke_kubernetes_version: "{{ kubernetes_version }}"

rke_force_configure: false

# This is the host that will run 'rke up'
# By default, use the first host in the play
rke_controller_hostname: "{{ ansible_play_hosts[0] }}"

# Networking configuration
#cluster_interface: "{{ ansible_default_ipv4.interface }}"
# cluster_cidr: "{{ [ansible_facts[cluster_interface].ipv4.network, ansible_facts[cluster_interface].ipv4.netmask] | join('/') | ipaddr('net') }}"

service_cluster_ip_range: "{{ kube_cni_services }}" #10.172.0.0/16
cluster_cidr: "{{ kube_cni_pod }}" #10.171.0.0/16


rke_ssh_user: rke_user
rke_node_roles: ['controlplane', 'etcd', 'worker']
rke_ssh_key_path: /home/rke_user/.ssh/id_rsa

kubectl_path: ""

# Setting the flannel network plug-in
rke_network_config:
  plugin: calico


rke_ingress_config:
  provider: nginx
  options:
    use-forwarded-headers: "true"

manifests_dir: "{{ ansible_env.HOME | default(ansible_env.PWD) | default('/root') }}/manifests"
