# Inventory example
k8s_cluster:
  children:
    masters:
      hosts:
        rnclab-mst1:
          ansible_host: 10.72.10.141
          rke2_type: server
        rnclab-mst2:
          ansible_host: 10.72.10.142
          rke2_type: server
        rnclab-mst3:
          ansible_host: 10.72.10.143
          rke2_type: server
